### ISSUE TITLE
IIFE useless

### ISSUE THREAD

**Issue by Johann-S** [helmutgranda/jquery-plugin-rollup-boilerplate#2]
You should remove the IIFE here: https://github.com/helmutgranda/jquery-plugin-rollup-boilerplate/blob/master/src/index.js#L4

We did the same in Bootstrap recently: https://github.com/twbs/bootstrap/pull/27314

**Comment by helmutgranda** [comment]
I didn't notice this comment earlier @Johann-S, thanks for the tip and getting right on it!
